@port = 3000
@hostname = localhost
@tcp = http
@api = users
@url = {{tcp}}://{{hostname}}:{{port}}
@resource_to_be_deleted = 1010723a-d52a-4d29-b6c3-6619bc337561
@resource_to_be_found = 1010723a-d52a-4d29-b6c3-6619bc337561
###

GET {{url}}/{{api}}

###

GET {{url}}/{{api}}/{{resource_to_be_found}}

###
POST {{url}}/user
Content-Type: application/json

{ "name":"Marios" }

###

DELETE {{url}}/{{api}}/{{resource_to_be_deleted}}
