GET http://localhost:3000/users

###

GET http://localhost:3000/users/d79bc06b-d6f4-4b74-9ace-9373128bb918

###
POST http://localhost:3000/user
Content-Type: application/json


{ "name":"Jane" }

###

DELETE http://localhost:3000/users/afeb9f2a-b405-48fb-9b36-417121a3d1d3
