@port = 3000
@hostname = localhost
@tcp = http
@api = users
@url = {{tcp}}://{{hostname}}:{{port}}
@resource_to_be_deleted = 5f786fd767370c1e8c4f1fd1
/* Comma seperated ids as query string */
@resources_to_be_deleted = 5f7f6b21e46645580885a591,5f7f68560c7fb53a60aedcd1,5f7f68841e672951d8b4dd7e,5f7f6924579f2f488c311025,5f7f68d3d863535038f20ddd
@resource_to_be_found = 5f77a612e9dd8e34d8b7d6ae
@resource_to_be_updated = 5f77a5069b518b2d40be8eb2

###

GET {{url}}/{{api}}

###
GET {{url}}/{{api}}/{{resource_to_be_found}}

###

POST {{url}}/{{api}}/create/user
Content-Type: application/json

{ 
	"name":"angelos",
	"email":"a.kolimitras@gmail.com34231",
	"password":"angelos123"
}

###

PATCH {{url}}/{{api}}/update/user/{{resource_to_be_updated}}
Content-Type: application/json

{ 
	"name":"Evangelos",
	"password": "evangelos234"
}

###

DELETE {{url}}/{{api}}/delete/user/{{resource_to_be_deleted}}

###

DELETE {{url}}/{{api}}/delete/users?users={{resources_to_be_deleted}}