@port = 3000
@hostname = localhost
@tcp = http
@api = users
@url = {{tcp}}://{{hostname}}:{{port}}
@resource_to_be_deleted = 5f786fd767370c1e8c4f1fd1
@resource_to_be_found = 5f77a612e9dd8e34d8b7d6ae
@resource_to_be_updated = 5f77a612e9dd8e34d8b7d6ae

###

GET {{url}}/{{api}}

###
GET {{url}}/{{api}}/{{resource_to_be_found}}

###

POST {{url}}/{{api}}/create/user
Content-Type: application/json

{ 
"name":"Sofia",
"email":"s.landerson@outlook.com"
}

###

PATCH {{url}}/{{api}}/update/user/{{resource_to_be_updated}}
Content-Type: application/json

{ 
"name":"Evangelos",
"email": "e.kolimitras@outlook.com"
}

###

DELETE {{url}}/{{api}}/delete/user/{{resource_to_be_deleted}}
